print('Home work lesson 6\n')

from bicycle import Bicycle
from electric_bicycle import ElectricBicycle

bicycle_1 = Bicycle('GT', 'Aggressor', 'Mountain', '27')
print(bicycle_1.get_description())
print()
bicycle_el = ElectricBicycle('Eltreco', 'INSIDER 350', 'Electric', '20', '350', '50')
print(bicycle_el.get_description())
bicycle_el.battery.describe_battery()
bicycle_el.read_odometr()
print()
bicycle_el.drive(10)
bicycle_el.charge_battery()
print(bicycle_el.battery_info())
print()
bicycle_el.drive(5)
bicycle_el.read_odometr()
print(bicycle_el.battery_info())
print()
bicycle_el.drive(25)
bicycle_el.charge_battery()
bicycle_el.drive(25)
bicycle_el.read_odometr()
