version: "3.5"

services:
  db:
    build:
      context: .
    volumes:
      - ./visitors/visitors/database:/var/app/database

  visitors:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./visitors/visitors:/var/app/
    depends_on:
      - db
