# Generated by Django 3.1.7 on 2021-04-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20210405_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='first_name',
            new_name='first',
        ),
    ]
