# Generated by Django 3.2 on 2021-04-26 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20210405_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=datetime.date.today)),
                ('number_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitors.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_visitors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor'),
        ),
    ]
