# Generated by Django 3.2 on 2021-04-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_auto_20210426_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
    ]
