# Generated by Django 3.2 on 2021-04-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_remove_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
